Repository AY2425S1-CS2103T-T17-1/tp, pull requests merged in 2024-10, with the labels that each got.

#31 Update developer guide: user profile, value proposition, user stories
  docs/DeveloperGuide.md
Labels: type.Task

#45 Add new contact
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Experience.java
  src/main/java/seedu/address/model/person/Interest.java
  src/main/java/seedu/address/model/person/Major.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/University.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: priority.High

#46 Update UI for add new contact feature
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#64 Fix checkstyle and addcommandparser test case
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/WorkExp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: due: Thursday

#71 Update UML diagrams with University
  README.md
  build.gradle
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByWorkExperienceCommandParserTest.java
Labels: due: Thursday

#77 Find work experience test cases
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: due: Thursday

#79 Update UML diagram
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: due: Thursday

#82 Update UML Diagram with Interest
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, due: Thursday

#85 Refactor Interest class to support comma-separated input
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Interest.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Bug, due: Thursday

#84 Add assert and testcase
  src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java
  src/main/java/seedu/address/logic/parser/AddWorkExperienceCommandParser.java
  src/test/java/seedu/address/logic/parser/AddWorkExperienceCommandParserTest.java
Labels: due: Thursday

#87 Update UML diagrams with WorkExp
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: due: Thursday

#89 Add testcases for AddWorkExperienceCommand and AddWorkExperienceCommandParser
  src/test/java/seedu/address/logic/commands/AddWorkExperienceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddWorkExperienceCommandParserTest.java
Labels: due: Thursday

#91 Add addi command for users to add interests to existing contacts
  src/main/java/seedu/address/logic/commands/AddInterestCommand.java
  src/main/java/seedu/address/logic/parser/AddInterestCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddInterestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddInterestCommandParserTest.java
Labels: priority.High, due: Thursday

#96 Fix person test and JsonSerializableAddressBook test
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: alpha-bug

#100 Update add interest feature
  src/main/java/seedu/address/logic/commands/AddInterestCommand.java
  src/main/java/seedu/address/logic/parser/AddInterestCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddInterestCommandTest.java
  src/test/java/seedu/address/logic/parser/AddInterestCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilderTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
  src/test/java/seedu/address/testutil/TypicalPersonsTest.java
Labels: alpha-bug

#103 Add tests for MajorContainsKeywords class
  src/main/java/seedu/address/model/person/Experience.java
  src/test/java/seedu/address/model/person/MajorContainsKeywordsPredicateTest.java
Labels: alpha-bug

#105 Add tests for FindByMajorCommand, FindByMajorCommandParser, FindByInterestCommandParser classes
  src/main/java/seedu/address/logic/parser/FindByMajorCommandParser.java
  src/test/java/seedu/address/logic/commands/FindByMajorCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByInterestCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindByMajorCommandParserTest.java
Labels: alpha-bug

#113 Update UI for find major and university commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindByMajorCommand.java
  src/main/java/seedu/address/logic/commands/FindByUniversityCommand.java
  src/main/java/seedu/address/model/person/MajorContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/UniversityContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindByMajorCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByUniversityCommandTest.java
Labels: due: Thursday

#115 Add logic for findm and findu command
  src/main/java/seedu/address/logic/commands/FindByMajorCommand.java
  src/main/java/seedu/address/logic/commands/FindByUniversityCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: due: Thursday
