Repository AY2425S1-CS2103T-T17-1/tp, pull requests merged in 2024-11, with the labels that each got.

#124 Update display message and logic for find commands
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindByInterestCommand.java
  src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java
  src/main/java/seedu/address/model/person/WorkExperienceContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindByInterestCommandTest.java
  src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java
Labels: due: Thursday

#132 Update user guide with findi
  docs/UserGuide.md
Labels: due: Thursday

#136 Update website
  docs/site.json
Labels: due: Thursday

#138 Update site.json to test website layout
  docs/site.json
Labels: type.Bug

#141 Add add work experience feature
  docs/UserGuide.md
Labels: due: Thursday

#150 Update user guide with 'findw' and 'findm' commands
  docs/UserGuide.md
Labels: due: Thursday

#152 Update error message for duplicate phone numbers
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/AddressBook.java
Labels: alpha-bug

#153 Fix display message for findw command
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java
  src/main/java/seedu/address/model/person/WorkExperienceContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindByWorkExperienceCommandTest.java
Labels: alpha-bug

#156 Fix display message for addw command
  src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java
  src/test/java/seedu/address/logic/commands/AddWorkExperienceCommandTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: alpha-bug

#161 Update work experience field to accept "&" symbol for addw command
  src/main/java/seedu/address/model/person/WorkExp.java
Labels: priority.High, alpha-bug

#162 Fix findi logic
  src/main/java/seedu/address/logic/commands/AddWorkExperienceCommand.java
  src/main/java/seedu/address/logic/parser/FindByInterestCommandParser.java
  src/main/java/seedu/address/model/person/InterestContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindByInterestCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByInterestCommandParserTest.java
Labels: due: Thursday, alpha-bug

#164 Update DG with findu and appendix:effort
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AB3Commands.puml
  docs/diagrams/UniVerseNewCommands.puml
Labels: due: Thursday

#166 Update workExp validation_regex to accept special symbols
  src/main/java/seedu/address/model/person/WorkExp.java
Labels: due: Thursday, alpha-bug

#170 Update team folder with my contributions
  docs/team/jeremy.md
Labels: due: Thursday

#176 Update DG
  docs/DeveloperGuide.md
Labels: due: Thursday

#178 Update DG with findm command
  docs/DeveloperGuide.md
Labels: due: Thursday

#187 Contribute to team folder
  docs/team/tzecheng.md
Labels: due: Thursday

#193 Fix findi bugs
  docs/team/chenle.md
  src/main/java/seedu/address/logic/parser/FindByInterestCommandParser.java
  src/main/java/seedu/address/model/person/InterestContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/commands/FindByInterestCommandTest.java
  src/test/java/seedu/address/logic/parser/FindByInterestCommandParserTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: severity.High, alpha-bug

#280 Update quick start in UG to have optional features
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: improveUG

#278 Update user stories to include edit command
  docs/DeveloperGuide.md
Labels: type.Bug, improveDG

#287 Update use case in dg
  docs/DeveloperGuide.md
Labels: improveDG

#288 Branch fix ug bug
  docs/UserGuide.md
Labels: improveUG, improveGUI, improveDG

#289 Update limitations with major
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/verakohh.md
Labels: improveUG, improveDG

#290 Update content page in UG
  docs/UserGuide.md
Labels: improveUG

#286 Improve documentation for findu, findm, findw, findi commands in UG
  docs/UserGuide.md
  docs/images/findPplCS.png
  docs/images/findPplSwimming.png
Labels: improveUG

#292 Update UG known issues section
  docs/UserGuide.md
Labels: due: Thursday, improveUG

#291 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: due: Thursday, improveUG, improveDG

#293 Update UG with birthday known issue
  docs/UserGuide.md
Labels: improveUG

#294 Fix app display to UniVerse
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MainWindowNew.fxml
Labels: due: Thursday

#295 Update DG with corrected findw use cases and broken documentation links
  docs/DeveloperGuide.md
Labels: due: Thursday, improveDG

#296 Add glossary ug
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: improveUG

#297 Update documents
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/kuiktzecheng.md
Labels: due: Thursday, improveUG, improveDG

#299 Update GUI
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: due: Thursday, improveGUI

#302 Update DG with planned enhancements
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/FindByMajorCommand.java
Labels: due: Thursday

#304 Update contributions section
  docs/team/jeremy.md
Labels: due: Thursday

#306 Update UG to v1.6
  docs/UserGuide.md
  docs/images/findPplCS.png
  docs/images/findwInternGoogle2024.png
  docs/images/helpMessage.png
Labels: improveUG

#308 Update known issues with missing birthday field
  docs/UserGuide.md
Labels: improveUG

#310 Update planned enhancements
  docs/DeveloperGuide.md
Labels: due: Thursday, improveDG

#314 Update DG to v1.6
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/improveErrorMsg.png
  docs/index.md
Labels: improveDG

#316 Edit display message for findw
  src/main/java/seedu/address/logic/commands/FindByWorkExperienceCommand.java
Labels: due: Thursday
